# Generated by Django 3.0.7 on 2020-10-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_remove_socketconnection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socketconnection',
            name='token',
        ),
    ]
