# Generated by Django 3.0.7 on 2020-10-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='ru', help_text='Language', max_length=5)),
                ('level', models.IntegerField(default='3', help_text='Level')),
                ('tp', models.CharField(default='questionend', help_text='Mode of quize', max_length=12)),
                ('mode', models.CharField(default='fullmatch', help_text='Type of matching', max_length=10)),
                ('question', models.TextField(verbose_name='Question')),
                ('answers', models.TextField(default='', help_text='Divided by coma', verbose_name='Answers')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default='1', help_text='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('questionend', 'Till questions are fineshed.'), ('infinite', 'Infinite quize (looping over questions).'), ('custom', 'Custom. Defining question by author.')], default='infinite', max_length=50, verbose_name='Quiz type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_done', models.BooleanField(default=False)),
                ('token', models.CharField(db_index=True, help_text='Token', max_length=100)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Question', verbose_name='Cur question')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('is_service', models.BooleanField(default=False)),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Room', verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smile', models.URLField(max_length=50, verbose_name='URL Smile')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.URLField(max_length=50, verbose_name='URL Sticker')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Alias')),
                ('name', models.CharField(help_text='Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', verbose_name='Question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Room', verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMessageSticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.RoomMessage', verbose_name='message')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Sticker', verbose_name='sticker')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMessageSmile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.RoomMessage', verbose_name='message')),
                ('smile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Smile', verbose_name='smile')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Theme'),
        ),
    ]
