# Generated by Django 3.0.7 on 2020-10-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='sticker',
        ),
        migrations.AddField(
            model_name='sticker',
            name='image',
            field=models.ImageField(default='', upload_to='sticker'),
            preserve_default=False,
        ),
    ]
