# Generated by Django 3.0.7 on 2020-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201029_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smile',
            name='smile',
        ),
        migrations.AddField(
            model_name='smile',
            name='image',
            field=models.ImageField(default='', upload_to='smile'),
            preserve_default=False,
        ),
    ]
