# Generated by Django 3.0.7 on 2020-10-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201029_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
