# Generated by Django 3.0.7 on 2020-10-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommessage',
            name='room',
        ),
    ]
