# Generated by Django 3.0.7 on 2020-10-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_roommessage_playername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommessagesmile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='roommessagesmile',
            name='smile',
        ),
        migrations.RemoveField(
            model_name='roommessagesticker',
            name='message',
        ),
        migrations.RemoveField(
            model_name='roommessagesticker',
            name='sticker',
        ),
        migrations.RemoveField(
            model_name='roomquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='roomquestion',
            name='room',
        ),
        migrations.AddField(
            model_name='player',
            name='account',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomMessageSmile',
        ),
        migrations.DeleteModel(
            name='RoomMessageSticker',
        ),
        migrations.DeleteModel(
            name='RoomQuestion',
        ),
    ]
