# Generated by Django 3.0.7 on 2020-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20201029_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(help_text='Name', max_length=100, unique=True),
        ),
    ]
