# Generated by Django 3.0.7 on 2020-11-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20201029_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='playerimage',
            field=models.CharField(default='', help_text='Name', max_length=200),
            preserve_default=False,
        ),
    ]
