# Generated by Django 3.0.7 on 2020-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_roommessage_playerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
